
package org.mes.jax.test.config;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DflDipService", targetNamespace = "http://impl.service.jax.mes.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DflDipService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doService", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.DoService")
    @ResponseWrapper(localName = "doServiceResponse", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.DoServiceResponse")
    @Action(input = "http://impl.service.jax.mes.org/DflDipService/doServiceRequest", output = "http://impl.service.jax.mes.org/DflDipService/doServiceResponse")
    public String doService(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "StopService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "StopService", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.StopService")
    @ResponseWrapper(localName = "StopServiceResponse", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.StopServiceResponse")
    @Action(input = "http://impl.service.jax.mes.org/DflDipService/StopServiceRequest", output = "http://impl.service.jax.mes.org/DflDipService/StopServiceResponse")
    public String stopService();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetTimeService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetTimeService", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.SetTimeService")
    @ResponseWrapper(localName = "SetTimeServiceResponse", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.SetTimeServiceResponse")
    @Action(input = "http://impl.service.jax.mes.org/DflDipService/SetTimeServiceRequest", output = "http://impl.service.jax.mes.org/DflDipService/SetTimeServiceResponse")
    public String setTimeService();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetTaktService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetTaktService", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.SetTaktService")
    @ResponseWrapper(localName = "SetTaktServiceResponse", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.SetTaktServiceResponse")
    @Action(input = "http://impl.service.jax.mes.org/DflDipService/SetTaktServiceRequest", output = "http://impl.service.jax.mes.org/DflDipService/SetTaktServiceResponse")
    public String setTaktService();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "StartService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "StartService", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.StartService")
    @ResponseWrapper(localName = "StartServiceResponse", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.StartServiceResponse")
    @Action(input = "http://impl.service.jax.mes.org/DflDipService/StartServiceRequest", output = "http://impl.service.jax.mes.org/DflDipService/StartServiceResponse")
    public String startService();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetID")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetID", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.SetID")
    @ResponseWrapper(localName = "SetIDResponse", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.SetIDResponse")
    @Action(input = "http://impl.service.jax.mes.org/DflDipService/SetIDRequest", output = "http://impl.service.jax.mes.org/DflDipService/SetIDResponse")
    public String setID();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetIP")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetIP", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.SetIP")
    @ResponseWrapper(localName = "SetIPResponse", targetNamespace = "http://impl.service.jax.mes.org/", className = "org.mes.jax.test.config.SetIPResponse")
    @Action(input = "http://impl.service.jax.mes.org/DflDipService/SetIPRequest", output = "http://impl.service.jax.mes.org/DflDipService/SetIPResponse")
    public String setIP();

}
