
package org.mes.jax.test.config;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DflDipServiceService", targetNamespace = "http://impl.service.jax.mes.org/", wsdlLocation = "http://localhost:8091/DflMesWebService/DflDipWebService?wsdl")
public class DflDipServiceService
    extends Service
{

    private final static URL DFLDIPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DFLDIPSERVICESERVICE_EXCEPTION;
    private final static QName DFLDIPSERVICESERVICE_QNAME = new QName("http://impl.service.jax.mes.org/", "DflDipServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/DflMesWebService/DflDipWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DFLDIPSERVICESERVICE_WSDL_LOCATION = url;
        DFLDIPSERVICESERVICE_EXCEPTION = e;
    }

    public DflDipServiceService() {
        super(__getWsdlLocation(), DFLDIPSERVICESERVICE_QNAME);
    }

    public DflDipServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DFLDIPSERVICESERVICE_QNAME, features);
    }

    public DflDipServiceService(URL wsdlLocation) {
        super(wsdlLocation, DFLDIPSERVICESERVICE_QNAME);
    }

    public DflDipServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DFLDIPSERVICESERVICE_QNAME, features);
    }

    public DflDipServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DflDipServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DflDipService
     */
    @WebEndpoint(name = "DflDipServicePort")
    public DflDipService getDflDipServicePort() {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "DflDipServicePort"), DflDipService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DflDipService
     */
    @WebEndpoint(name = "DflDipServicePort")
    public DflDipService getDflDipServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "DflDipServicePort"), DflDipService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DFLDIPSERVICESERVICE_EXCEPTION!= null) {
            throw DFLDIPSERVICESERVICE_EXCEPTION;
        }
        return DFLDIPSERVICESERVICE_WSDL_LOCATION;
    }

}
