
package org.mes.jax.test.config;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MachineListenerService", targetNamespace = "http://impl.service.jax.mes.org/", wsdlLocation = "http://localhost:8091/DflMesWebService/MachineListener?wsdl")
public class MachineListenerService
    extends Service
{

    private final static URL MACHINELISTENERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MACHINELISTENERSERVICE_EXCEPTION;
    private final static QName MACHINELISTENERSERVICE_QNAME = new QName("http://impl.service.jax.mes.org/", "MachineListenerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/DflMesWebService/MachineListener?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MACHINELISTENERSERVICE_WSDL_LOCATION = url;
        MACHINELISTENERSERVICE_EXCEPTION = e;
    }

    public MachineListenerService() {
        super(__getWsdlLocation(), MACHINELISTENERSERVICE_QNAME);
    }

    public MachineListenerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MACHINELISTENERSERVICE_QNAME, features);
    }

    public MachineListenerService(URL wsdlLocation) {
        super(wsdlLocation, MACHINELISTENERSERVICE_QNAME);
    }

    public MachineListenerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MACHINELISTENERSERVICE_QNAME, features);
    }

    public MachineListenerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MachineListenerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MachineListener
     */
    @WebEndpoint(name = "MachineListenerPort")
    public MachineListener getMachineListenerPort() {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "MachineListenerPort"), MachineListener.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MachineListener
     */
    @WebEndpoint(name = "MachineListenerPort")
    public MachineListener getMachineListenerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "MachineListenerPort"), MachineListener.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MACHINELISTENERSERVICE_EXCEPTION!= null) {
            throw MACHINELISTENERSERVICE_EXCEPTION;
        }
        return MACHINELISTENERSERVICE_WSDL_LOCATION;
    }

}
