
package org.mes.jax.test.config;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScadaTaktServiceService", targetNamespace = "http://impl.service.jax.mes.org/", wsdlLocation = "http://localhost:8091/DflMesWebService/ScadaTaktService?wsdl")
public class ScadaTaktServiceService
    extends Service
{

    private final static URL SCADATAKTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCADATAKTSERVICESERVICE_EXCEPTION;
    private final static QName SCADATAKTSERVICESERVICE_QNAME = new QName("http://impl.service.jax.mes.org/", "ScadaTaktServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/DflMesWebService/ScadaTaktService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCADATAKTSERVICESERVICE_WSDL_LOCATION = url;
        SCADATAKTSERVICESERVICE_EXCEPTION = e;
    }

    public ScadaTaktServiceService() {
        super(__getWsdlLocation(), SCADATAKTSERVICESERVICE_QNAME);
    }

    public ScadaTaktServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCADATAKTSERVICESERVICE_QNAME, features);
    }

    public ScadaTaktServiceService(URL wsdlLocation) {
        super(wsdlLocation, SCADATAKTSERVICESERVICE_QNAME);
    }

    public ScadaTaktServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCADATAKTSERVICESERVICE_QNAME, features);
    }

    public ScadaTaktServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScadaTaktServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScadaTaktService
     */
    @WebEndpoint(name = "ScadaTaktServicePort")
    public ScadaTaktService getScadaTaktServicePort() {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaTaktServicePort"), ScadaTaktService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScadaTaktService
     */
    @WebEndpoint(name = "ScadaTaktServicePort")
    public ScadaTaktService getScadaTaktServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaTaktServicePort"), ScadaTaktService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCADATAKTSERVICESERVICE_EXCEPTION!= null) {
            throw SCADATAKTSERVICESERVICE_EXCEPTION;
        }
        return SCADATAKTSERVICESERVICE_WSDL_LOCATION;
    }

}
