
package org.mes.jax.test.config;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScadaConvduraServiceService", targetNamespace = "http://impl.service.jax.mes.org/", wsdlLocation = "http://localhost:8091/DflMesWebService/ScadaConvduraService?wsdl")
public class ScadaConvduraServiceService
    extends Service
{

    private final static URL SCADACONVDURASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCADACONVDURASERVICESERVICE_EXCEPTION;
    private final static QName SCADACONVDURASERVICESERVICE_QNAME = new QName("http://impl.service.jax.mes.org/", "ScadaConvduraServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/DflMesWebService/ScadaConvduraService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCADACONVDURASERVICESERVICE_WSDL_LOCATION = url;
        SCADACONVDURASERVICESERVICE_EXCEPTION = e;
    }

    public ScadaConvduraServiceService() {
        super(__getWsdlLocation(), SCADACONVDURASERVICESERVICE_QNAME);
    }

    public ScadaConvduraServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCADACONVDURASERVICESERVICE_QNAME, features);
    }

    public ScadaConvduraServiceService(URL wsdlLocation) {
        super(wsdlLocation, SCADACONVDURASERVICESERVICE_QNAME);
    }

    public ScadaConvduraServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCADACONVDURASERVICESERVICE_QNAME, features);
    }

    public ScadaConvduraServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScadaConvduraServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScadaConvduraService
     */
    @WebEndpoint(name = "ScadaConvduraServicePort")
    public ScadaConvduraService getScadaConvduraServicePort() {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaConvduraServicePort"), ScadaConvduraService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScadaConvduraService
     */
    @WebEndpoint(name = "ScadaConvduraServicePort")
    public ScadaConvduraService getScadaConvduraServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaConvduraServicePort"), ScadaConvduraService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCADACONVDURASERVICESERVICE_EXCEPTION!= null) {
            throw SCADACONVDURASERVICESERVICE_EXCEPTION;
        }
        return SCADACONVDURASERVICESERVICE_WSDL_LOCATION;
    }

}
