
package org.mes.jax.test.config;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScadaTdowntimeServiceService", targetNamespace = "http://impl.service.jax.mes.org/", wsdlLocation = "http://localhost:8091/DflMesWebService/ScadaTdowntimeService?wsdl")
public class ScadaTdowntimeServiceService
    extends Service
{

    private final static URL SCADATDOWNTIMESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCADATDOWNTIMESERVICESERVICE_EXCEPTION;
    private final static QName SCADATDOWNTIMESERVICESERVICE_QNAME = new QName("http://impl.service.jax.mes.org/", "ScadaTdowntimeServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/DflMesWebService/ScadaTdowntimeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCADATDOWNTIMESERVICESERVICE_WSDL_LOCATION = url;
        SCADATDOWNTIMESERVICESERVICE_EXCEPTION = e;
    }

    public ScadaTdowntimeServiceService() {
        super(__getWsdlLocation(), SCADATDOWNTIMESERVICESERVICE_QNAME);
    }

    public ScadaTdowntimeServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCADATDOWNTIMESERVICESERVICE_QNAME, features);
    }

    public ScadaTdowntimeServiceService(URL wsdlLocation) {
        super(wsdlLocation, SCADATDOWNTIMESERVICESERVICE_QNAME);
    }

    public ScadaTdowntimeServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCADATDOWNTIMESERVICESERVICE_QNAME, features);
    }

    public ScadaTdowntimeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScadaTdowntimeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScadaTdowntimeService
     */
    @WebEndpoint(name = "ScadaTdowntimeServicePort")
    public ScadaTdowntimeService getScadaTdowntimeServicePort() {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaTdowntimeServicePort"), ScadaTdowntimeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScadaTdowntimeService
     */
    @WebEndpoint(name = "ScadaTdowntimeServicePort")
    public ScadaTdowntimeService getScadaTdowntimeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaTdowntimeServicePort"), ScadaTdowntimeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCADATDOWNTIMESERVICESERVICE_EXCEPTION!= null) {
            throw SCADATDOWNTIMESERVICESERVICE_EXCEPTION;
        }
        return SCADATDOWNTIMESERVICESERVICE_WSDL_LOCATION;
    }

}
