
package org.mes.jax.test.config;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScadaPressService", targetNamespace = "http://service.jax.mes.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScadaPressService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doService", targetNamespace = "http://service.jax.mes.org/", className = "org.sunny.client.config.DoService")
    @ResponseWrapper(localName = "doServiceResponse", targetNamespace = "http://service.jax.mes.org/", className = "org.sunny.client.config.DoServiceResponse")
    @Action(input = "http://service.jax.mes.org/ScadaPressService/doServiceRequest", output = "http://service.jax.mes.org/ScadaPressService/doServiceResponse")
    public String doService(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0);

}
