
package org.mes.jax.test.config;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScadaProdduraServiceService", targetNamespace = "http://service.jax.mes.org/", wsdlLocation = "http://localhost:8091/DflMesWebService/ScadaProdduraService?wsdl")
public class ScadaProdduraServiceService
    extends Service
{

    private final static URL SCADAPRODDURASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCADAPRODDURASERVICESERVICE_EXCEPTION;
    private final static QName SCADAPRODDURASERVICESERVICE_QNAME = new QName("http://service.jax.mes.org/", "ScadaProdduraServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/DflMesWebService/ScadaProdduraService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCADAPRODDURASERVICESERVICE_WSDL_LOCATION = url;
        SCADAPRODDURASERVICESERVICE_EXCEPTION = e;
    }

    public ScadaProdduraServiceService() {
        super(__getWsdlLocation(), SCADAPRODDURASERVICESERVICE_QNAME);
    }

    public ScadaProdduraServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCADAPRODDURASERVICESERVICE_QNAME, features);
    }

    public ScadaProdduraServiceService(URL wsdlLocation) {
        super(wsdlLocation, SCADAPRODDURASERVICESERVICE_QNAME);
    }

    public ScadaProdduraServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCADAPRODDURASERVICESERVICE_QNAME, features);
    }

    public ScadaProdduraServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScadaProdduraServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScadaProdduraService
     */
    @WebEndpoint(name = "ScadaProdduraServicePort")
    public ScadaProdduraService getScadaProdduraServicePort() {
        return super.getPort(new QName("http://service.jax.mes.org/", "ScadaProdduraServicePort"), ScadaProdduraService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScadaProdduraService
     */
    @WebEndpoint(name = "ScadaProdduraServicePort")
    public ScadaProdduraService getScadaProdduraServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.jax.mes.org/", "ScadaProdduraServicePort"), ScadaProdduraService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCADAPRODDURASERVICESERVICE_EXCEPTION!= null) {
            throw SCADAPRODDURASERVICESERVICE_EXCEPTION;
        }
        return SCADAPRODDURASERVICESERVICE_WSDL_LOCATION;
    }

}
