
package org.mes.jax.test.config;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScadaPrdstsServiceService", targetNamespace = "http://service.jax.mes.org/", wsdlLocation = "http://localhost:8091/DflMesWebService/ScadaPrdstsService?wsdl")
public class ScadaPrdstsServiceService
    extends Service
{

    private final static URL SCADAPRDSTSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCADAPRDSTSSERVICESERVICE_EXCEPTION;
    private final static QName SCADAPRDSTSSERVICESERVICE_QNAME = new QName("http://service.jax.mes.org/", "ScadaPrdstsServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/DflMesWebService/ScadaPrdstsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCADAPRDSTSSERVICESERVICE_WSDL_LOCATION = url;
        SCADAPRDSTSSERVICESERVICE_EXCEPTION = e;
    }

    public ScadaPrdstsServiceService() {
        super(__getWsdlLocation(), SCADAPRDSTSSERVICESERVICE_QNAME);
    }

    public ScadaPrdstsServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCADAPRDSTSSERVICESERVICE_QNAME, features);
    }

    public ScadaPrdstsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SCADAPRDSTSSERVICESERVICE_QNAME);
    }

    public ScadaPrdstsServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCADAPRDSTSSERVICESERVICE_QNAME, features);
    }

    public ScadaPrdstsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScadaPrdstsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScadaPrdstsService
     */
    @WebEndpoint(name = "ScadaPrdstsServicePort")
    public ScadaPrdstsService getScadaPrdstsServicePort() {
        return super.getPort(new QName("http://service.jax.mes.org/", "ScadaPrdstsServicePort"), ScadaPrdstsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScadaPrdstsService
     */
    @WebEndpoint(name = "ScadaPrdstsServicePort")
    public ScadaPrdstsService getScadaPrdstsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.jax.mes.org/", "ScadaPrdstsServicePort"), ScadaPrdstsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCADAPRDSTSSERVICESERVICE_EXCEPTION!= null) {
            throw SCADAPRDSTSSERVICESERVICE_EXCEPTION;
        }
        return SCADAPRDSTSSERVICESERVICE_WSDL_LOCATION;
    }

}
