
package org.mes.jax.test.config;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScadaTemperServiceService", targetNamespace = "http://impl.service.jax.mes.org/", wsdlLocation = "http://localhost:8091/DflMesWebService/ScadaTemperService?wsdl")
public class ScadaTemperServiceService
    extends Service
{

    private final static URL SCADATEMPERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCADATEMPERSERVICESERVICE_EXCEPTION;
    private final static QName SCADATEMPERSERVICESERVICE_QNAME = new QName("http://impl.service.jax.mes.org/", "ScadaTemperServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/DflMesWebService/ScadaTemperService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCADATEMPERSERVICESERVICE_WSDL_LOCATION = url;
        SCADATEMPERSERVICESERVICE_EXCEPTION = e;
    }

    public ScadaTemperServiceService() {
        super(__getWsdlLocation(), SCADATEMPERSERVICESERVICE_QNAME);
    }

    public ScadaTemperServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCADATEMPERSERVICESERVICE_QNAME, features);
    }

    public ScadaTemperServiceService(URL wsdlLocation) {
        super(wsdlLocation, SCADATEMPERSERVICESERVICE_QNAME);
    }

    public ScadaTemperServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCADATEMPERSERVICESERVICE_QNAME, features);
    }

    public ScadaTemperServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScadaTemperServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScadaTemperService
     */
    @WebEndpoint(name = "ScadaTemperServicePort")
    public ScadaTemperService getScadaTemperServicePort() {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaTemperServicePort"), ScadaTemperService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScadaTemperService
     */
    @WebEndpoint(name = "ScadaTemperServicePort")
    public ScadaTemperService getScadaTemperServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaTemperServicePort"), ScadaTemperService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCADATEMPERSERVICESERVICE_EXCEPTION!= null) {
            throw SCADATEMPERSERVICESERVICE_EXCEPTION;
        }
        return SCADATEMPERSERVICESERVICE_WSDL_LOCATION;
    }

}
