
package org.mes.jax.test.config;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScadaTprodduraServiceService", targetNamespace = "http://service.jax.mes.org/", wsdlLocation = "http://localhost:8091/DflMesWebService/ScadaTprodduraService?wsdl")
public class ScadaTprodduraServiceService
    extends Service
{

    private final static URL SCADATPRODDURASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCADATPRODDURASERVICESERVICE_EXCEPTION;
    private final static QName SCADATPRODDURASERVICESERVICE_QNAME = new QName("http://service.jax.mes.org/", "ScadaTprodduraServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/DflMesWebService/ScadaTprodduraService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCADATPRODDURASERVICESERVICE_WSDL_LOCATION = url;
        SCADATPRODDURASERVICESERVICE_EXCEPTION = e;
    }

    public ScadaTprodduraServiceService() {
        super(__getWsdlLocation(), SCADATPRODDURASERVICESERVICE_QNAME);
    }

    public ScadaTprodduraServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCADATPRODDURASERVICESERVICE_QNAME, features);
    }

    public ScadaTprodduraServiceService(URL wsdlLocation) {
        super(wsdlLocation, SCADATPRODDURASERVICESERVICE_QNAME);
    }

    public ScadaTprodduraServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCADATPRODDURASERVICESERVICE_QNAME, features);
    }

    public ScadaTprodduraServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScadaTprodduraServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScadaTprodduraService
     */
    @WebEndpoint(name = "ScadaTprodduraServicePort")
    public ScadaTprodduraService getScadaTprodduraServicePort() {
        return super.getPort(new QName("http://service.jax.mes.org/", "ScadaTprodduraServicePort"), ScadaTprodduraService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScadaTprodduraService
     */
    @WebEndpoint(name = "ScadaTprodduraServicePort")
    public ScadaTprodduraService getScadaTprodduraServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.jax.mes.org/", "ScadaTprodduraServicePort"), ScadaTprodduraService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCADATPRODDURASERVICESERVICE_EXCEPTION!= null) {
            throw SCADATPRODDURASERVICESERVICE_EXCEPTION;
        }
        return SCADATPRODDURASERVICESERVICE_WSDL_LOCATION;
    }

}
