
package org.mes.jax.test.config;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScadaStdcapServiceService", targetNamespace = "http://impl.service.jax.mes.org/", wsdlLocation = "http://localhost:8091/DflMesWebService/ScadaStdcapService?wsdl")
public class ScadaStdcapServiceService
    extends Service
{

    private final static URL SCADASTDCAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCADASTDCAPSERVICESERVICE_EXCEPTION;
    private final static QName SCADASTDCAPSERVICESERVICE_QNAME = new QName("http://impl.service.jax.mes.org/", "ScadaStdcapServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/DflMesWebService/ScadaStdcapService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCADASTDCAPSERVICESERVICE_WSDL_LOCATION = url;
        SCADASTDCAPSERVICESERVICE_EXCEPTION = e;
    }

    public ScadaStdcapServiceService() {
        super(__getWsdlLocation(), SCADASTDCAPSERVICESERVICE_QNAME);
    }

    public ScadaStdcapServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCADASTDCAPSERVICESERVICE_QNAME, features);
    }

    public ScadaStdcapServiceService(URL wsdlLocation) {
        super(wsdlLocation, SCADASTDCAPSERVICESERVICE_QNAME);
    }

    public ScadaStdcapServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCADASTDCAPSERVICESERVICE_QNAME, features);
    }

    public ScadaStdcapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScadaStdcapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScadaStdcapService
     */
    @WebEndpoint(name = "ScadaStdcapServicePort")
    public ScadaStdcapService getScadaStdcapServicePort() {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaStdcapServicePort"), ScadaStdcapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScadaStdcapService
     */
    @WebEndpoint(name = "ScadaStdcapServicePort")
    public ScadaStdcapService getScadaStdcapServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaStdcapServicePort"), ScadaStdcapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCADASTDCAPSERVICESERVICE_EXCEPTION!= null) {
            throw SCADASTDCAPSERVICESERVICE_EXCEPTION;
        }
        return SCADASTDCAPSERVICESERVICE_WSDL_LOCATION;
    }

}
