
package org.mes.jax.test.config;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScadaProdqtyServiceService", targetNamespace = "http://impl.service.jax.mes.org/", wsdlLocation = "http://localhost:8091/DflMesWebService/ScadaProdqtyService?wsdl")
public class ScadaProdqtyServiceService
    extends Service
{

    private final static URL SCADAPRODQTYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCADAPRODQTYSERVICESERVICE_EXCEPTION;
    private final static QName SCADAPRODQTYSERVICESERVICE_QNAME = new QName("http://impl.service.jax.mes.org/", "ScadaProdqtyServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/DflMesWebService/ScadaProdqtyService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCADAPRODQTYSERVICESERVICE_WSDL_LOCATION = url;
        SCADAPRODQTYSERVICESERVICE_EXCEPTION = e;
    }

    public ScadaProdqtyServiceService() {
        super(__getWsdlLocation(), SCADAPRODQTYSERVICESERVICE_QNAME);
    }

    public ScadaProdqtyServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCADAPRODQTYSERVICESERVICE_QNAME, features);
    }

    public ScadaProdqtyServiceService(URL wsdlLocation) {
        super(wsdlLocation, SCADAPRODQTYSERVICESERVICE_QNAME);
    }

    public ScadaProdqtyServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCADAPRODQTYSERVICESERVICE_QNAME, features);
    }

    public ScadaProdqtyServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScadaProdqtyServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScadaProdqtyService
     */
    @WebEndpoint(name = "ScadaProdqtyServicePort")
    public ScadaProdqtyService getScadaProdqtyServicePort() {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaProdqtyServicePort"), ScadaProdqtyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScadaProdqtyService
     */
    @WebEndpoint(name = "ScadaProdqtyServicePort")
    public ScadaProdqtyService getScadaProdqtyServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaProdqtyServicePort"), ScadaProdqtyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCADAPRODQTYSERVICESERVICE_EXCEPTION!= null) {
            throw SCADAPRODQTYSERVICESERVICE_EXCEPTION;
        }
        return SCADAPRODQTYSERVICESERVICE_WSDL_LOCATION;
    }

}
