
package org.mes.jax.test.config;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScadaDowntimeServiceService", targetNamespace = "http://impl.service.jax.mes.org/", wsdlLocation = "http://localhost:8091/DflMesWebService/ScadaDowntimeService?wsdl")
public class ScadaDowntimeServiceService
    extends Service
{

    private final static URL SCADADOWNTIMESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCADADOWNTIMESERVICESERVICE_EXCEPTION;
    private final static QName SCADADOWNTIMESERVICESERVICE_QNAME = new QName("http://impl.service.jax.mes.org/", "ScadaDowntimeServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8091/DflMesWebService/ScadaDowntimeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCADADOWNTIMESERVICESERVICE_WSDL_LOCATION = url;
        SCADADOWNTIMESERVICESERVICE_EXCEPTION = e;
    }

    public ScadaDowntimeServiceService() {
        super(__getWsdlLocation(), SCADADOWNTIMESERVICESERVICE_QNAME);
    }

    public ScadaDowntimeServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCADADOWNTIMESERVICESERVICE_QNAME, features);
    }

    public ScadaDowntimeServiceService(URL wsdlLocation) {
        super(wsdlLocation, SCADADOWNTIMESERVICESERVICE_QNAME);
    }

    public ScadaDowntimeServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCADADOWNTIMESERVICESERVICE_QNAME, features);
    }

    public ScadaDowntimeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScadaDowntimeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScadaDowntimeService
     */
    @WebEndpoint(name = "ScadaDowntimeServicePort")
    public ScadaDowntimeService getScadaDowntimeServicePort() {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaDowntimeServicePort"), ScadaDowntimeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScadaDowntimeService
     */
    @WebEndpoint(name = "ScadaDowntimeServicePort")
    public ScadaDowntimeService getScadaDowntimeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.jax.mes.org/", "ScadaDowntimeServicePort"), ScadaDowntimeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCADADOWNTIMESERVICESERVICE_EXCEPTION!= null) {
            throw SCADADOWNTIMESERVICESERVICE_EXCEPTION;
        }
        return SCADADOWNTIMESERVICESERVICE_WSDL_LOCATION;
    }

}
